version: "3.8"
services:
  rootService:
    image: emedilife
    container_name: api_emedilife
    volumes:
      - emedilife_volumes:/usr/src/app/api_emedilife
    ports:
      - "5000:5000"
    networks:
      - emedilife_network
    environment:
      - HOST=localhost
      - PORT=5000


networks:
  mynet:
    driver: bridge

volumes:
      emedilife_volumes: